spring.application.name=vt-main

# =====================================================
# ============  No Virtual Threads Config  ============
# =====================================================
#server.tomcat.threads.max=10
#spring.threads.virtual.enabled=false


# =====================================================
# =============  Virtual Threads Config  ==============
# =====================================================
spring.threads.virtual.enabled=true
